### ISSUE TITLE
fail to run "ember server"

### ISSUE THREAD

**Issue by litao10422** [xdumaine/ember-webrtc#1]
1. git clone https://github.com/xdumaine/ember-webrtc
2. cd ember-webrtc
3. npm install
4. bower install
5. ember server
-> error message
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
ENOENT: no such file or directory, stat 'C:\MyDvlp\Ember-Learn\WebRTC\ember-webrtc\tmp\concat_with_maps-input_base_path-XclVnSeu.tmp\0\bower_components\socket.io-client\socket.io.js'

Informations:
ember-cli: 3.0.0
OS: windows 10. win32 x64

**Comment by xdumaine** [comment]
@litao10422 this repo is garbage, sorry. it has no value, and has never had development done on it.
